=== SusanaCasMed/DAW-LENGUAJE-MARCAS-SUSANA-CASTILLO/cifp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="cifp">
    <xs:complexType>
      <xs:sequence>
      <xs:element ref="alumne" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="professor" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
  </xs:complexType>
  </xs:element>


  <!--ALUMNE-->
  <xs:element name="alumne">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="llinatges"/>
        <xs:element ref="data_naixement" minOccurs="0"/><!--puede no aparecer-, opcional-->
        <xs:element ref="correu" minOccurs="0"/>
        <xs:element ref="telefon" minOccurs="0"/>
        <xs:element ref="adreça" minOccurs="0"/>
        <xs:element ref="data_matricula"/>
        <xs:element ref="curs"/>
      </xs:sequence>
      <xs:attribute name="alumne_id" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>

  <!--PROFESSOR-->
  <xs:element name="professor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="llinatges"/>
        <xs:element ref="data_naixement" minOccurs="0"/>
        <xs:element ref="correu" minOccurs="0"/>
        <xs:element ref="telefon" minOccurs="0"/>
        <xs:element ref="adreça" minOccurs="0"/>
        <xs:element ref="data_incorporacio"/>
        <xs:element ref="departament"/>
        <xs:element ref="assignatura" minOccurs="0" maxOccurs="unbounded"/><!--puede aparecer una o más veces-->
      </xs:sequence>
      <xs:attribute name="professor_id" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>

  <!--assignatura-->
  <xs:element name="assignatura">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom_assignatura"/>
        <xs:element ref="data_inici" minOccurs="0"/>
        <xs:element ref="data_final" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="assignatura_id" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- elemntos simples-->
  <xs:element name="nom" type="xs:string"/>
  <xs:element name="llinatges" type="xs:string"/>
  <xs:element name="data_naixement" type="xs:string"/>
  <xs:element name="correu" type="xs:string"/>
  <xs:element name="telefon" type="xs:string"/>
  <xs:element name="adreça" type="xs:string"/>
  <xs:element name="data_matricula" type="xs:string"/>
  <xs:element name="curs" type="xs:string"/>
  <xs:element name="data_incorporacio" type="xs:string"/>
  <xs:element name="data_inici" type="xs:string"/>
  <xs:element name="data_final" type="xs:string"/>

  <!--atributos valroes restringidos-->
  <xs:element name="departament">
   <xs:complexType>
   <xs:attribute name="tipus" use="required">
    <xs:simpleType>
     <xs:restriction base="xs:string">
     <xs:enumeration value="INFORMATICA"/>
     <xs:enumeration value="ELECTRICITAT"/>
     <xs:enumeration value="AUTOMOCIO"/>
     </xs:restriction>
    </xs:simpleType>
    </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="nom_assignatura">
  <xs:complexType>
   <xs:attribute name="cicle" use="required">
   <xs:simpleType>
   <xs:restriction base="xs:string">
   <xs:enumeration value="DAW"/>
   <xs:enumeration value="DAM"/>
   <xs:enumeration value="ASIX"/>
   <xs:enumeration value="SMX"/>
   <xs:enumeration value="SEIA"/>
   <xs:enumeration value="ER"/>
    <xs:enumeration value="AUT"/>
    </xs:restriction>
    </xs:simpleType>
    </xs:attribute>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== SusanaCasMed/DAW-LENGUAJE-MARCAS-SUSANA-CASTILLO/cifpXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<cifp
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="cifp.xsd">

<alumne alumne_id="1">
  <nom></nom>
    <llinatges></llinatges>
      <data_naixement></data_naixement>
      <correu></correu>
      <telefon></telefon>
      <adreça></adreça>
      <data_matricula></data_matricula>
      <curs></curs>
</alumne>
    
<professor professor_id="2">
    <nom></nom>
    <llinatges></llinatges>
      <data_naixement></data_naixement>
      <correu></correu>
      <telefon></telefon>
      <adreça></adreça>
      <data_incorporacio></data_incorporacio>
      <departament tipus="INFORMATICA"></departament>
      
<assignatura assignatura_id="3"> <!--OJO EN XML-XSD CAMBIADO A NUMERO (NO ALUMN1) PORQUE COMO ES TIPO INTEGER NO LO VALIDABA-->
          <nom_assignatura cicle="DAW"></nom_assignatura>
          <data_inici></data_inici>
          <data_final></data_final>
</assignatura>
</professor>

</cifp>
