=== SusanaCasMed/DAW-LENGUAJE-MARCAS-SUSANA-CASTILLO/cifp.dtd
<!ELEMENT cifp (alumne*, professor*)>

<!ELEMENT alumne (nom, llinatges, data_naixement?, correu?, telefon?, adreça?, data_matricula, curs)>
<!ELEMENT professor (nom, llinatges, data_naixement?, correu?, telefon?, adreça?, data_incorporacio, departament, assignatura*)>
<!ELEMENT assignatura (nom_assignatura, data_inici?, data_final?)>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT llinatges (#PCDATA)>
<!ELEMENT data_naixement (#PCDATA)>
<!ELEMENT correu (#PCDATA)> 
<!ELEMENT telefon (#PCDATA)> 
<!ELEMENT adreça (#PCDATA)>
<!ELEMENT data_matricula (#PCDATA)> 
<!ELEMENT curs (#PCDATA)> 
<!ELEMENT data_incorporacio (#PCDATA)>
<!ELEMENT departament (#PCDATA)>
<!ELEMENT nom_assignatura (#PCDATA)>
<!ELEMENT data_inici  (#PCDATA)>
<!ELEMENT data_final (#PCDATA)>


<!ATTLIST alumne alumne_id ID #REQUIRED>
<!ATTLIST professor professor_id ID #REQUIRED>
<!ATTLIST departament tipus (INFORMATICA | ELECTRONICA | AUTOMOCIO) #REQUIRED>
<!ATTLIST assignatura assignatura_id ID #REQUIRED>
<!ATTLIST nom_assignatura cicle (DAW | DAM | ASIX | SMX | SEIA | ER | AUT) #REQUIRED>

=== SusanaCasMed/DAW-LENGUAJE-MARCAS-SUSANA-CASTILLO/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cifp SYSTEM 'cifp.dtd'>

<cifp>
<alumne alumne_id="ALUM1"> <!-- NO PUEDE SER SOLO UN NÚMERO, TIENE QUE TENER LETRAS, EJEMPLO VIDEO HACER  CON NUMERO Y CAMBIAR o poner numero en id y tipo dato cdDATA-->
  <nom></nom>
    <llinatges></llinatges>
      <data_naixement></data_naixement>
      <correu></correu>
      <telefon></telefon>
      <adreça></adreça>
      <data_matricula></data_matricula>
      <curs></curs>
</alumne>
    
<professor professor_id="PROF2">
    <nom></nom>
    <llinatges></llinatges>
      <data_naixement></data_naixement>
      <correu></correu>
      <telefon></telefon>
      <adreça></adreça>
      <data_incorporacio></data_incorporacio>
      <departament tipus="INFORMATICA"></departament>
      
<assignatura assignatura_id="ASSIG3">
          <nom_assignatura cicle="DAW"></nom_assignatura>
          <data_inici></data_inici>
          <data_final></data_final>
</assignatura>
</professor>
</cifp>
